data_dir: /data/a3-data/

# setting num_workers -1 will use all available cpu cores
num_workers: 16
pin_memory: false
batch_size: 16
backend: cv2

download_images: false
skip_image_check: true

image_size: 512

interpolation: 3
# 3 - INTER_AREA / bicubic
# 1 - INTER_LINEAR / bilinear

normalize_stats:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
