run:
  dir: ./outputs/${project}/${hydra.job.override_dirname}
sweep:
  dir: ./outputs/${project}/
  subdir: ${hydra.job.override_dirname}
job:
  config:
    override_dirname:
      exclude_keys:
        - xp.resume
